# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
      r_binary_packages:
        - gsl
      r_github_packages:
        - r-lib/covr
      addons:
        apt:
          packages:
            - libgsl23
            - g++
    - os: osx
      r: release
      addons:
        homebrew:
          packages:
            - gsl
      r_binary_packages:
        - gsl


notifications:
  email:
    on_success: change
    on_failure: change

after_success:
    - Rscript -e 'covr::codecov()'
